spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/electronicsystem?serverTimezone=GMT%2B8&useSSL=true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
